/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.controllers.FieldController;
import core.controllers.PlayerLoaderController;
import core.controllers.utils.Response;
import core.models.Field;
import core.models.Player;
import graph.GraphVisualizer;
import graph.MyGraph;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.graphstream.ui.view.View;

/**
 *
 * @author natal
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public Field field;
    public MyGraph myGraph;
    //List<Player> players;
    public JFileChooser fileChooser;
    public static String file;
    public MainView() {
        field = new Field();
        myGraph = new MyGraph();
        //players = new ArrayList();
        fileChooser = new JFileChooser();
        file = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DaPanel = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        greetin_lbl = new javax.swing.JLabel();
        start_btn = new javax.swing.JLabel();
        text_lbl = new javax.swing.JLabel();
        exit_btn = new javax.swing.JLabel();
        upload_btn = new javax.swing.JLabel();
        Results = new javax.swing.JPanel();
        greetin_lbl1 = new javax.swing.JLabel();
        switch_btn = new javax.swing.JLabel();
        home_btn3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        img1_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        img1_lbl1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        greetin_lbl2 = new javax.swing.JLabel();
        greetin_lbl3 = new javax.swing.JLabel();
        home_btn4 = new javax.swing.JLabel();
        greetin_lbl4 = new javax.swing.JLabel();
        Strat2 = new javax.swing.JPanel();
        choose_lbl = new javax.swing.JLabel();
        Opt1_btn2 = new javax.swing.JLabel();
        Opt2_btn2 = new javax.swing.JLabel();
        Opt3_btn2 = new javax.swing.JLabel();
        home_btn2 = new javax.swing.JLabel();
        Strat1 = new javax.swing.JPanel();
        choose_lbl1 = new javax.swing.JLabel();
        Opt1_btn = new javax.swing.JLabel();
        Opt2_btn = new javax.swing.JLabel();
        Opt3_btn = new javax.swing.JLabel();
        home_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DaPanel.setBackground(new java.awt.Color(255, 255, 204));
        DaPanel.setPreferredSize(new java.awt.Dimension(1240, 610));
        DaPanel.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(255, 255, 204));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetin_lbl.setBackground(new java.awt.Color(153, 51, 0));
        greetin_lbl.setFont(new java.awt.Font("Sergio Trendy", 0, 36)); // NOI18N
        greetin_lbl.setForeground(new java.awt.Color(153, 51, 0));
        greetin_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetin_lbl.setText("<html> Hello there. <br> Welcome, let s lay a game.");
        greetin_lbl.setFocusTraversalPolicyProvider(true);
        greetin_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.add(greetin_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 640, 80));

        start_btn.setBackground(new java.awt.Color(255, 102, 0));
        start_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        start_btn.setForeground(new java.awt.Color(255, 255, 204));
        start_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start_btn.setText("Start");
        start_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        start_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start_btn.setInheritsPopupMenu(false);
        start_btn.setOpaque(true);
        start_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                start_btnMousePressed(evt);
            }
        });
        Home.add(start_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 280, 79));

        text_lbl.setBackground(new java.awt.Color(153, 51, 0));
        text_lbl.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        text_lbl.setForeground(new java.awt.Color(153, 51, 0));
        text_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_lbl.setFocusTraversalPolicyProvider(true);
        text_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.add(text_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 480, 40));

        exit_btn.setBackground(new java.awt.Color(255, 102, 0));
        exit_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 204));
        exit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_btn.setText("Leave");
        exit_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn.setInheritsPopupMenu(false);
        exit_btn.setOpaque(true);
        exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit_btnMousePressed(evt);
            }
        });
        Home.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 79));

        upload_btn.setBackground(new java.awt.Color(255, 102, 0));
        upload_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        upload_btn.setForeground(new java.awt.Color(255, 255, 204));
        upload_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upload_btn.setText("Upload");
        upload_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        upload_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upload_btn.setInheritsPopupMenu(false);
        upload_btn.setOpaque(true);
        upload_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                upload_btnMousePressed(evt);
            }
        });
        Home.add(upload_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 220, 79));

        DaPanel.add(Home, "card2");

        Results.setBackground(new java.awt.Color(255, 255, 204));
        Results.setForeground(new java.awt.Color(225, 204, 204));
        Results.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetin_lbl1.setBackground(new java.awt.Color(153, 51, 0));
        greetin_lbl1.setFont(new java.awt.Font("Sergio Trendy", 0, 14)); // NOI18N
        greetin_lbl1.setForeground(new java.awt.Color(153, 51, 0));
        greetin_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetin_lbl1.setText("End Player");
        greetin_lbl1.setFocusTraversalPolicyProvider(true);
        greetin_lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Results.add(greetin_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 80, 20));

        switch_btn.setBackground(new java.awt.Color(255, 102, 0));
        switch_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        switch_btn.setForeground(new java.awt.Color(255, 255, 204));
        switch_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        switch_btn.setText("Change Strat");
        switch_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        switch_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        switch_btn.setInheritsPopupMenu(false);
        switch_btn.setOpaque(true);
        switch_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                switch_btnMousePressed(evt);
            }
        });
        Results.add(switch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 220, 79));

        home_btn3.setBackground(new java.awt.Color(255, 102, 0));
        home_btn3.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        home_btn3.setForeground(new java.awt.Color(255, 255, 204));
        home_btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn3.setText("Show Result");
        home_btn3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        home_btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn3.setInheritsPopupMenu(false);
        home_btn3.setOpaque(true);
        home_btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btn3MousePressed(evt);
            }
        });
        Results.add(home_btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 220, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setForeground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new java.awt.BorderLayout());
        Results.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 330, 350));

        img1_lbl.setBackground(new java.awt.Color(255, 255, 153));
        img1_lbl.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        img1_lbl.setForeground(new java.awt.Color(255, 204, 204));
        img1_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1_lbl.setText("Image Here");
        img1_lbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        img1_lbl.setOpaque(true);
        Results.add(img1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 300, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());
        Results.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 330, 350));

        img1_lbl1.setBackground(new java.awt.Color(255, 255, 153));
        img1_lbl1.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        img1_lbl1.setForeground(new java.awt.Color(255, 204, 204));
        img1_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1_lbl1.setText("Image Here");
        img1_lbl1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        img1_lbl1.setOpaque(true);
        Results.add(img1_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 300, 300));

        jTextField1.setBackground(new java.awt.Color(225, 225, 153));
        jTextField1.setForeground(new java.awt.Color(225, 204, 204));
        jTextField1.setCaretColor(new java.awt.Color(225, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Results.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 120, -1));

        jTextField2.setBackground(new java.awt.Color(225, 225, 153));
        Results.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, 120, -1));

        greetin_lbl2.setBackground(new java.awt.Color(153, 51, 0));
        greetin_lbl2.setFont(new java.awt.Font("Sergio Trendy", 0, 14)); // NOI18N
        greetin_lbl2.setForeground(new java.awt.Color(153, 51, 0));
        greetin_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetin_lbl2.setFocusTraversalPolicyProvider(true);
        greetin_lbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Results.add(greetin_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1220, 80));

        greetin_lbl3.setBackground(new java.awt.Color(153, 51, 0));
        greetin_lbl3.setFont(new java.awt.Font("Sergio Trendy", 0, 14)); // NOI18N
        greetin_lbl3.setForeground(new java.awt.Color(153, 51, 0));
        greetin_lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetin_lbl3.setText("Start Player");
        greetin_lbl3.setFocusTraversalPolicyProvider(true);
        greetin_lbl3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Results.add(greetin_lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 90, 20));

        home_btn4.setBackground(new java.awt.Color(255, 102, 0));
        home_btn4.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        home_btn4.setForeground(new java.awt.Color(255, 255, 204));
        home_btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn4.setText("Home");
        home_btn4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        home_btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn4.setInheritsPopupMenu(false);
        home_btn4.setOpaque(true);
        home_btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_btn4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btn4MousePressed(evt);
            }
        });
        Results.add(home_btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 220, 79));

        greetin_lbl4.setBackground(new java.awt.Color(153, 51, 0));
        greetin_lbl4.setFont(new java.awt.Font("Sergio Trendy", 0, 36)); // NOI18N
        greetin_lbl4.setForeground(new java.awt.Color(153, 51, 0));
        greetin_lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetin_lbl4.setText("Here are the results");
        greetin_lbl4.setFocusTraversalPolicyProvider(true);
        greetin_lbl4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Results.add(greetin_lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 570, 80));

        DaPanel.add(Results, "card5");

        Strat2.setBackground(new java.awt.Color(255, 255, 204));
        Strat2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choose_lbl.setBackground(new java.awt.Color(153, 51, 0));
        choose_lbl.setFont(new java.awt.Font("Sergio Trendy", 0, 40)); // NOI18N
        choose_lbl.setForeground(new java.awt.Color(153, 51, 0));
        choose_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choose_lbl.setText("Now, choose a tactic");
        choose_lbl.setFocusTraversalPolicyProvider(true);
        choose_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Strat2.add(choose_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 640, 80));

        Opt1_btn2.setBackground(new java.awt.Color(255, 102, 0));
        Opt1_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt1_btn2.setForeground(new java.awt.Color(255, 255, 204));
        Opt1_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt1_btn2.setText("No tactics");
        Opt1_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt1_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt1_btn2.setOpaque(true);
        Opt1_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Opt1_btn2MousePressed(evt);
            }
        });
        Strat2.add(Opt1_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 330, 50));

        Opt2_btn2.setBackground(new java.awt.Color(255, 102, 0));
        Opt2_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt2_btn2.setForeground(new java.awt.Color(255, 255, 204));
        Opt2_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt2_btn2.setText("4-4-3");
        Opt2_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt2_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt2_btn2.setOpaque(true);
        Opt2_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Opt2_btn2MousePressed(evt);
            }
        });
        Strat2.add(Opt2_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 330, 50));

        Opt3_btn2.setBackground(new java.awt.Color(255, 102, 0));
        Opt3_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt3_btn2.setForeground(new java.awt.Color(255, 255, 204));
        Opt3_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt3_btn2.setText("4-4-2");
        Opt3_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt3_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt3_btn2.setOpaque(true);
        Opt3_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Opt3_btn2MousePressed(evt);
            }
        });
        Strat2.add(Opt3_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 330, 50));

        home_btn2.setBackground(new java.awt.Color(255, 102, 0));
        home_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        home_btn2.setForeground(new java.awt.Color(255, 255, 204));
        home_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn2.setText("Back");
        home_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        home_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn2.setInheritsPopupMenu(false);
        home_btn2.setOpaque(true);
        home_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btn2MousePressed(evt);
            }
        });
        Strat2.add(home_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 79));

        DaPanel.add(Strat2, "card3");

        Strat1.setBackground(new java.awt.Color(255, 255, 204));
        Strat1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choose_lbl1.setBackground(new java.awt.Color(153, 51, 0));
        choose_lbl1.setFont(new java.awt.Font("Sergio Trendy", 0, 40)); // NOI18N
        choose_lbl1.setForeground(new java.awt.Color(153, 51, 0));
        choose_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choose_lbl1.setText("Now, choose a strategy");
        choose_lbl1.setFocusTraversalPolicyProvider(true);
        choose_lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Strat1.add(choose_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 640, 80));

        Opt1_btn.setBackground(new java.awt.Color(255, 102, 0));
        Opt1_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt1_btn.setForeground(new java.awt.Color(255, 255, 204));
        Opt1_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt1_btn.setText("Speed");
        Opt1_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt1_btn.setOpaque(true);
        Opt1_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Opt1_btnMousePressed(evt);
            }
        });
        Strat1.add(Opt1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 330, 50));

        Opt2_btn.setBackground(new java.awt.Color(255, 102, 0));
        Opt2_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt2_btn.setForeground(new java.awt.Color(255, 255, 204));
        Opt2_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt2_btn.setText("Shots");
        Opt2_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt2_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt2_btn.setOpaque(true);
        Opt2_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Opt2_btnMousePressed(evt);
            }
        });
        Strat1.add(Opt2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 330, 50));

        Opt3_btn.setBackground(new java.awt.Color(255, 102, 0));
        Opt3_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt3_btn.setForeground(new java.awt.Color(255, 255, 204));
        Opt3_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt3_btn.setText("Possession");
        Opt3_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt3_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt3_btn.setOpaque(true);
        Opt3_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Opt3_btnMousePressed(evt);
            }
        });
        Strat1.add(Opt3_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 330, 50));

        home_btn.setBackground(new java.awt.Color(255, 102, 0));
        home_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        home_btn.setForeground(new java.awt.Color(255, 255, 204));
        home_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn.setText("Back");
        home_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.setInheritsPopupMenu(false);
        home_btn.setOpaque(true);
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btnMousePressed(evt);
            }
        });
        Strat1.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 79));

        DaPanel.add(Strat1, "card3");

        getContentPane().add(DaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_btnMousePressed

    private void start_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_btnMousePressed
        // TODO add your handling code here:
        
        Response response = PlayerLoaderController.loadPlayersFromCSV(file, field);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            DaPanel.removeAll();
            DaPanel.add(Strat1);
            DaPanel.repaint();
            DaPanel.revalidate();
        }
    }//GEN-LAST:event_start_btnMousePressed

    private void upload_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upload_btnMousePressed
        // TODO add your handling code here
        // Crear un JFileChooser
        fileChooser = new JFileChooser();
        
        // Mostrar el diálogo para seleccionar archivos
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            File selectedFile = fileChooser.getSelectedFile();
            file = selectedFile.getAbsolutePath().replace("\\", "/");
        }
        text_lbl.setText(file);
    }//GEN-LAST:event_upload_btnMousePressed

    private void home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMousePressed
        // TODO add your handling code here:
        DaPanel.removeAll();
        DaPanel.add(Home);
        DaPanel.repaint();
        DaPanel.revalidate();
    }//GEN-LAST:event_home_btnMousePressed

    private void Opt1_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt1_btnMousePressed
        // TODO add your handling code here:
        field.setStrategy("speed");
        DaPanel.removeAll();
        DaPanel.add(Strat2);
        DaPanel.repaint();
        DaPanel.revalidate();
    }//GEN-LAST:event_Opt1_btnMousePressed

    private void Opt2_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt2_btnMousePressed
        // TODO add your handling code here:
        field.setStrategy("shot");
        DaPanel.removeAll();
        DaPanel.add(Strat2);
        DaPanel.repaint();
        DaPanel.revalidate();
    }//GEN-LAST:event_Opt2_btnMousePressed

    private void Opt3_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt3_btnMousePressed
        // TODO add your handling code here:
        field.setStrategy("possession");
        DaPanel.removeAll();
        DaPanel.add(Strat2);
        DaPanel.repaint();
        DaPanel.revalidate();
    }//GEN-LAST:event_Opt3_btnMousePressed

    private void home_btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btn2MousePressed
        // TODO add your handling code here:
        DaPanel.removeAll();
        DaPanel.add(Strat1);
        DaPanel.repaint();
        DaPanel.revalidate();
    }//GEN-LAST:event_home_btn2MousePressed

    private void Opt1_btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt1_btn2MousePressed
        // TODO add your handling code here:
        // Define the adjacency matrix
        int[][] adjacencyMatrix = {
            {0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0},
            {0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0},
            {0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0},
            {0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1},
            {0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0}
        };
                
        myGraph.createGraphFromAdjacencyMatrix(adjacencyMatrix, field.getPlayers());
        field.setMyGraph(myGraph);
        DaPanel.removeAll();
        DaPanel.add(Results);
        DaPanel.repaint();
        DaPanel.revalidate();
        jPanel1.removeAll();
        System.setProperty("org.graphstream.ui", "swing");
        GraphVisualizer.addGraphToPanel(GraphVisualizer.visualizeGraph(myGraph), jPanel1);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_Opt1_btn2MousePressed

    private void Opt2_btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt2_btn2MousePressed
        // TODO add your handling code here:
        int[][] adjacencyMatrix = {
            {0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0},
            {0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0},
            {0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0},
            {0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1},
            {0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0}
        };
        
        myGraph.createGraphFromAdjacencyMatrix(adjacencyMatrix, field.getPlayers());
        field.setMyGraph(myGraph);
        DaPanel.removeAll();
        DaPanel.add(Results);
        DaPanel.repaint();
        DaPanel.revalidate();
        jPanel1.removeAll();
        System.setProperty("org.graphstream.ui", "swing");
        GraphVisualizer.addGraphToPanel(GraphVisualizer.visualizeGraph(myGraph), jPanel1);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_Opt2_btn2MousePressed

    private void home_btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btn3MousePressed
        List<Player> d = new ArrayList();

        // TODO add your handling code here:
        Response response = FieldController.findOptimalPath(field, jTextField1.getText(), jTextField2.getText(), d);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            jPanel3.removeAll();
            greetin_lbl2.setText(d.toString());
            System.setProperty("org.graphstream.ui", "swing");
            //View v = GraphVisualizer.visualizeGraph(MyGraph.GraphFromList(d)).display().getDefaultView();
            GraphVisualizer.addGraphToPanel(GraphVisualizer.visualizeGraph(MyGraph.GraphFromList(d)), jPanel3);
            jPanel3.repaint();
            jPanel3.revalidate();
        }
        
    }//GEN-LAST:event_home_btn3MousePressed

    private void switch_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_btnMousePressed
        // TODO add your handling code here:
        jPanel3.removeAll();
        DaPanel.removeAll();
        DaPanel.add(Strat1);
        DaPanel.repaint();
        DaPanel.revalidate();
    }//GEN-LAST:event_switch_btnMousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel1.removeAll();
        DaPanel.removeAll();
        DaPanel.add(Home);
        DaPanel.repaint();
        DaPanel.revalidate();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void home_btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btn4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_btn4MousePressed

    private void Opt3_btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt3_btn2MousePressed
        // TODO add your handling code here:
        int[][] adjacencyMatrix = {
            {0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0},
            {1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0},
            {0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0},
            {0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0},
            {0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1},
            {0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1},
            {0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0}
        };
        
        myGraph.createGraphFromAdjacencyMatrix(adjacencyMatrix, field.getPlayers());
        field.setMyGraph(myGraph);
        DaPanel.removeAll();
        DaPanel.add(Results);
        DaPanel.repaint();
        DaPanel.revalidate();
        jPanel1.removeAll();
        System.setProperty("org.graphstream.ui", "swing");
        GraphVisualizer.addGraphToPanel(GraphVisualizer.visualizeGraph(myGraph), jPanel1);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_Opt3_btn2MousePressed

    private void home_btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btn4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_home_btn4MouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DaPanel;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Opt1_btn;
    private javax.swing.JLabel Opt1_btn2;
    private javax.swing.JLabel Opt2_btn;
    private javax.swing.JLabel Opt2_btn2;
    private javax.swing.JLabel Opt3_btn;
    private javax.swing.JLabel Opt3_btn2;
    private javax.swing.JPanel Results;
    private javax.swing.JPanel Strat1;
    private javax.swing.JPanel Strat2;
    private javax.swing.JLabel choose_lbl;
    private javax.swing.JLabel choose_lbl1;
    private javax.swing.JLabel exit_btn;
    private javax.swing.JLabel greetin_lbl;
    private javax.swing.JLabel greetin_lbl1;
    private javax.swing.JLabel greetin_lbl2;
    private javax.swing.JLabel greetin_lbl3;
    private javax.swing.JLabel greetin_lbl4;
    private javax.swing.JLabel home_btn;
    private javax.swing.JLabel home_btn2;
    private javax.swing.JLabel home_btn3;
    private javax.swing.JLabel home_btn4;
    private javax.swing.JLabel img1_lbl;
    private javax.swing.JLabel img1_lbl1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel start_btn;
    private javax.swing.JLabel switch_btn;
    private javax.swing.JLabel text_lbl;
    private javax.swing.JLabel upload_btn;
    // End of variables declaration//GEN-END:variables
}
