/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

/**
 *
 * @author natal
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DaPanel = new javax.swing.JPanel();
        Results = new javax.swing.JPanel();
        greetin_lbl1 = new javax.swing.JLabel();
        img1_lbl = new javax.swing.JLabel();
        switch_btn = new javax.swing.JLabel();
        home_btn3 = new javax.swing.JLabel();
        img1_lbl1 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        greetin_lbl = new javax.swing.JLabel();
        start_btn = new javax.swing.JLabel();
        text_lbl = new javax.swing.JLabel();
        exit_btn = new javax.swing.JLabel();
        upload_btn = new javax.swing.JLabel();
        Strat2 = new javax.swing.JPanel();
        choose_lbl = new javax.swing.JLabel();
        Opt1_btn2 = new javax.swing.JLabel();
        Opt2_btn2 = new javax.swing.JLabel();
        Opt3_btn2 = new javax.swing.JLabel();
        home_btn2 = new javax.swing.JLabel();
        Strat1 = new javax.swing.JPanel();
        choose_lbl1 = new javax.swing.JLabel();
        Opt1_btn = new javax.swing.JLabel();
        Opt2_btn = new javax.swing.JLabel();
        Opt3_btn = new javax.swing.JLabel();
        home_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DaPanel.setBackground(new java.awt.Color(255, 255, 204));
        DaPanel.setPreferredSize(new java.awt.Dimension(1240, 610));
        DaPanel.setLayout(new java.awt.CardLayout());

        Results.setBackground(new java.awt.Color(255, 255, 204));
        Results.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetin_lbl1.setBackground(new java.awt.Color(153, 51, 0));
        greetin_lbl1.setFont(new java.awt.Font("Sergio Trendy", 0, 36)); // NOI18N
        greetin_lbl1.setForeground(new java.awt.Color(153, 51, 0));
        greetin_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetin_lbl1.setText("Here are the results");
        greetin_lbl1.setFocusTraversalPolicyProvider(true);
        greetin_lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Results.add(greetin_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 570, 80));

        img1_lbl.setBackground(new java.awt.Color(255, 255, 153));
        img1_lbl.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        img1_lbl.setForeground(new java.awt.Color(255, 204, 204));
        img1_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1_lbl.setText("Image Here");
        img1_lbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        img1_lbl.setOpaque(true);
        Results.add(img1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 300, 300));

        switch_btn.setBackground(new java.awt.Color(255, 102, 0));
        switch_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        switch_btn.setForeground(new java.awt.Color(255, 255, 204));
        switch_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        switch_btn.setText("Change Start");
        switch_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        switch_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        switch_btn.setInheritsPopupMenu(false);
        switch_btn.setOpaque(true);
        Results.add(switch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, 220, 79));

        home_btn3.setBackground(new java.awt.Color(255, 102, 0));
        home_btn3.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        home_btn3.setForeground(new java.awt.Color(255, 255, 204));
        home_btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn3.setText("Home");
        home_btn3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        home_btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn3.setInheritsPopupMenu(false);
        home_btn3.setOpaque(true);
        Results.add(home_btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 220, 79));

        img1_lbl1.setBackground(new java.awt.Color(255, 255, 153));
        img1_lbl1.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        img1_lbl1.setForeground(new java.awt.Color(255, 204, 204));
        img1_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1_lbl1.setText("Image Here");
        img1_lbl1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        img1_lbl1.setOpaque(true);
        Results.add(img1_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 300, 300));

        DaPanel.add(Results, "card5");

        Home.setBackground(new java.awt.Color(255, 255, 204));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetin_lbl.setBackground(new java.awt.Color(153, 51, 0));
        greetin_lbl.setFont(new java.awt.Font("Sergio Trendy", 0, 36)); // NOI18N
        greetin_lbl.setForeground(new java.awt.Color(153, 51, 0));
        greetin_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetin_lbl.setText("<html> Hello there. <br> Welcome, let s lay a game.");
        greetin_lbl.setFocusTraversalPolicyProvider(true);
        greetin_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.add(greetin_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 640, 80));

        start_btn.setBackground(new java.awt.Color(255, 102, 0));
        start_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        start_btn.setForeground(new java.awt.Color(255, 255, 204));
        start_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start_btn.setText("Start");
        start_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        start_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start_btn.setInheritsPopupMenu(false);
        start_btn.setOpaque(true);
        Home.add(start_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 280, 79));

        text_lbl.setBackground(new java.awt.Color(153, 51, 0));
        text_lbl.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        text_lbl.setForeground(new java.awt.Color(153, 51, 0));
        text_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_lbl.setText("Here s some random text, idk what for");
        text_lbl.setFocusTraversalPolicyProvider(true);
        text_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.add(text_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 480, 40));

        exit_btn.setBackground(new java.awt.Color(255, 102, 0));
        exit_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 204));
        exit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_btn.setText("Leave");
        exit_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn.setInheritsPopupMenu(false);
        exit_btn.setOpaque(true);
        Home.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 79));

        upload_btn.setBackground(new java.awt.Color(255, 102, 0));
        upload_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        upload_btn.setForeground(new java.awt.Color(255, 255, 204));
        upload_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upload_btn.setText("Upload");
        upload_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        upload_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upload_btn.setInheritsPopupMenu(false);
        upload_btn.setOpaque(true);
        Home.add(upload_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 220, 79));

        DaPanel.add(Home, "card2");

        Strat2.setBackground(new java.awt.Color(255, 255, 204));
        Strat2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choose_lbl.setBackground(new java.awt.Color(153, 51, 0));
        choose_lbl.setFont(new java.awt.Font("Sergio Trendy", 0, 40)); // NOI18N
        choose_lbl.setForeground(new java.awt.Color(153, 51, 0));
        choose_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choose_lbl.setText("Now, choose a strategy");
        choose_lbl.setFocusTraversalPolicyProvider(true);
        choose_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Strat2.add(choose_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 640, 80));

        Opt1_btn2.setBackground(new java.awt.Color(255, 102, 0));
        Opt1_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt1_btn2.setForeground(new java.awt.Color(255, 255, 204));
        Opt1_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt1_btn2.setText("Would you choose this ");
        Opt1_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt1_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt1_btn2.setOpaque(true);
        Strat2.add(Opt1_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 330, 50));

        Opt2_btn2.setBackground(new java.awt.Color(255, 102, 0));
        Opt2_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt2_btn2.setForeground(new java.awt.Color(255, 255, 204));
        Opt2_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt2_btn2.setText("Or maybe this");
        Opt2_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt2_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt2_btn2.setOpaque(true);
        Strat2.add(Opt2_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 330, 50));

        Opt3_btn2.setBackground(new java.awt.Color(255, 102, 0));
        Opt3_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt3_btn2.setForeground(new java.awt.Color(255, 255, 204));
        Opt3_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt3_btn2.setText("What about this");
        Opt3_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt3_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt3_btn2.setOpaque(true);
        Strat2.add(Opt3_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 330, 50));

        home_btn2.setBackground(new java.awt.Color(255, 102, 0));
        home_btn2.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        home_btn2.setForeground(new java.awt.Color(255, 255, 204));
        home_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn2.setText("Back");
        home_btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        home_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn2.setInheritsPopupMenu(false);
        home_btn2.setOpaque(true);
        Strat2.add(home_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 79));

        DaPanel.add(Strat2, "card3");

        Strat1.setBackground(new java.awt.Color(255, 255, 204));
        Strat1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choose_lbl1.setBackground(new java.awt.Color(153, 51, 0));
        choose_lbl1.setFont(new java.awt.Font("Sergio Trendy", 0, 40)); // NOI18N
        choose_lbl1.setForeground(new java.awt.Color(153, 51, 0));
        choose_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choose_lbl1.setText("Now, choose a strategy");
        choose_lbl1.setFocusTraversalPolicyProvider(true);
        choose_lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Strat1.add(choose_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 640, 80));

        Opt1_btn.setBackground(new java.awt.Color(255, 102, 0));
        Opt1_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt1_btn.setForeground(new java.awt.Color(255, 255, 204));
        Opt1_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt1_btn.setText("Choose this one");
        Opt1_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt1_btn.setOpaque(true);
        Strat1.add(Opt1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 330, 50));

        Opt2_btn.setBackground(new java.awt.Color(255, 102, 0));
        Opt2_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt2_btn.setForeground(new java.awt.Color(255, 255, 204));
        Opt2_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt2_btn.setText("Or maybe this one");
        Opt2_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt2_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt2_btn.setOpaque(true);
        Strat1.add(Opt2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 330, 50));

        Opt3_btn.setBackground(new java.awt.Color(255, 102, 0));
        Opt3_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 18)); // NOI18N
        Opt3_btn.setForeground(new java.awt.Color(255, 255, 204));
        Opt3_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Opt3_btn.setText("What about this here");
        Opt3_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        Opt3_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opt3_btn.setOpaque(true);
        Strat1.add(Opt3_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 330, 50));

        home_btn.setBackground(new java.awt.Color(255, 102, 0));
        home_btn.setFont(new java.awt.Font("Sergio Trendy", 0, 24)); // NOI18N
        home_btn.setForeground(new java.awt.Color(255, 255, 204));
        home_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_btn.setText("Back");
        home_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(153, 51, 0)));
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.setInheritsPopupMenu(false);
        home_btn.setOpaque(true);
        Strat1.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 79));

        DaPanel.add(Strat1, "card3");

        getContentPane().add(DaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DaPanel;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Opt1_btn;
    private javax.swing.JLabel Opt1_btn2;
    private javax.swing.JLabel Opt2_btn;
    private javax.swing.JLabel Opt2_btn2;
    private javax.swing.JLabel Opt3_btn;
    private javax.swing.JLabel Opt3_btn2;
    private javax.swing.JPanel Results;
    private javax.swing.JPanel Strat1;
    private javax.swing.JPanel Strat2;
    private javax.swing.JLabel choose_lbl;
    private javax.swing.JLabel choose_lbl1;
    private javax.swing.JLabel exit_btn;
    private javax.swing.JLabel greetin_lbl;
    private javax.swing.JLabel greetin_lbl1;
    private javax.swing.JLabel home_btn;
    private javax.swing.JLabel home_btn2;
    private javax.swing.JLabel home_btn3;
    private javax.swing.JLabel img1_lbl;
    private javax.swing.JLabel img1_lbl1;
    private javax.swing.JLabel start_btn;
    private javax.swing.JLabel switch_btn;
    private javax.swing.JLabel text_lbl;
    private javax.swing.JLabel upload_btn;
    // End of variables declaration//GEN-END:variables
}
